### ISSUE TITLE
Browser example

### ISSUE THREAD

**Issue by ArturPrzybysz** [GMOD/bgzf-filehandle#10]
As in topic; could you add to readme how to access bgziped file in browser?

**Comment by ArturPrzybysz** [comment]
Is it sufficient to just pass a Blob instead of path to BgzfFilehandle?

**Comment by cmdcolin** [comment]
@ArturPrzybysz I have been promoting using this package https://github.com/GMOD/generic-filehandle which includes a "Blob filehandle" that can be used with this package 

I didn't test it with this package specifically but it should be usable. You can pass the "filehandle" and "gziFilehandle" arguments to the constructor object e.g.

```
import {RemoteFile,BlobFile} from 'generic-filehandle'
const fd1 = new BgzFilehandle({ gziFilehandle: new RemoteFile(...), filehandle: new RemoteFile(...)})
const fd2 = new BgzFilehandle({ gziFilehandle: new BlobFile(...), filehandle: new BlobFile(...)})
```

**Comment by ArturPrzybysz** [comment]
@cmdcolin Thank you for response.
I am trying to use your libraries like this:
```
const f = new BgzfFilehandle({gziFilehandle: new BlobFile(indexBlob), filehandle: new BlobFile(bgzipBlob)});
const stats = f.stat();
```
Where indexBlob is blob of test.vcf.gz.gzi, test.vcf.gz is bgzipped test.vcf. Its data comes from [this example](http://www.internationalgenome.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40/).

However I am getting an error: 
```
Uncaught (in promise) Error: read error
    at BgzFilehandle._callee2$ (bgzFilehandle.js:38)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```
Can you suggest what am I doing wrong?

**Comment by cmdcolin** [comment]
For VCF, I would recommend using "tabix" indexes (tbi) unless you have a use case for gzi index with vcf (in which case I'd be curious). Our module https://github.com/GMOD/tabix-js is designed for this.

In either case I might check out this error still, I'll report back

**Comment by ArturPrzybysz** [comment]
Works like a charm! Big love for your work, thank you.

**Comment by ArturPrzybysz** [comment]
I know it is not a part of this issue or even same library, however could you explain what is `refName` parameter in getLine?
```
lines = [];
await tbiIndexed.getLines('ctgA', 200, 300, (line, fileOffset) => lines.push(line));
```
In example it has value 'ctgA'.

What should be my approach if I want to iterate over all data lines in a file?

**Comment by garrettjstevens** [comment]
Hmm, that's not usually how we use tabix-js. To get started you could do 
```js
refNames = await tbiIndexed.getReferenceSequenceNames()
```
to get an array of reference sequence names, and then do `getLines` for each refName in the array. That doesn't tell you what to use for start and end, though. If you don't know them, you can just go from 0 to some huge number and it will probably be ok.

**Comment by cmdcolin** [comment]
Tribble index actually has this low level iteration over all blocks in the file functionality

https://github.com/GMOD/tribble-index-js

**Comment by cmdcolin** [comment]
Alternatively that technique to iterate over all reference sequences as @garrettjstevens pointed out would work

**Comment by garrettjstevens** [comment]
I added a feature request in tabix-js for making it easier to get all lines from a refName: https://github.com/GMOD/tabix-js/issues/24

**Comment by ArturPrzybysz** [comment]
Thank you, it works!
